In [1]:
import os
import pandas as pd

In [42]:
# illustrate the intersection
# of two lists in most simple way
def intersection(lst1, lst2):
    lst3 = [value for value in lst1 if value in lst2]
    return lst3


#write the x and y csv for each site
def write_xy_files(site_name, df_site, weathers, air_pollutions, output_folder):
    df = pd.read_csv(data_folder+site_name+'.csv')
    
    #extract the included x features and y features
    df_x = df[intersection(['code']+weathers+times, df.columns)]
    df_y = df[intersection(air_pollutions, df.columns)]
    #rename the code column for the later merge with site info
    df_x = df_x.rename(columns={"code": "ap_code"})
    
    #merge x dataframe with the site info
    df_x = df_x.merge(df_site, how='left', on=['ap_code'])
    
    df_x.to_csv(output_folder+site_name+'_x.csv', index=False)
    df_y.to_csv(output_folder+site_name+'_y.csv', index=False)

In [18]:
air_pollutions = ['nox','no2','no','pm2.5','pm10']
weathers = ['ws', 'wd', 'vis', 'temp', 'pressure', 'RH']
times = ['date_unix', 'week', 'weekday', 'hour', 'month', 'day_julian']
weathers_2 = ['ssr', 'tp', 'blh', 'tcc', 'sp', 'tc']

In [39]:
data_folder = "D:/Work/污染项目/data-overall/data/"
site_info_path = "D:/Work/污染项目/data-overall/siteinfo.csv"
output_folder = "D:/Work/污染项目/data-overall/data_process/before_engineer/"

In [14]:
df_site = pd.read_csv(site_info_path)
#drop the Site and met columns, cause we already have their code column
df_site = df_site.drop(['Site', 'met'], axis=1)
df_site

  ap_code     ap_lat   ap_long  MetCode    met_lat  met_long site
0     MY1  51.522530 -0.154611    37720  51.479167 -0.450556   UT
1     KC1  51.521050 -0.213492    37720  51.479167 -0.450556   UB
2    BIRR  52.476140 -1.874978    35340  52.453889 -1.748056   UT
3    BRS8  51.462839 -2.584482    37243  51.382778 -2.719167   UB
4    LED6  53.819970 -1.576361    33463  53.611667 -1.666944   UT
5    LEED  53.803780 -1.546472    33463  53.611667 -1.666944   UB
6    ABD7  57.144550 -2.106472    30910  57.205000 -2.205278   UT
7      AH  52.503850 -3.034178    35200  52.243056 -2.885833   RB
8    SCN2  53.586340 -0.636811    33735  53.306944 -0.548056   UI
9    YK11  53.951890 -1.075861    32660  54.043591 -1.250316   UT

In [8]:
csv_files = os.listdir(data_folder)
csv_files = [item for item in csv_files if item.endswith('.csv')]

In [44]:
#output the x and y files for each site
for site_name in csv_files:
    site_name = site_name[:-4]
    write_xy_files(site_name, 
                   df_site, 
                   weathers, 
                   air_pollutions, 
                   output_folder)